name: full_picker
description: A Flutter package that helps you select files in different modes.
version: 2.1.0
homepage: https://github.com/mbfakourii/full_picker
repository: https://github.com/mbfakourii/full_picker
issue_tracker: https://github.com/mbfakourii/full_picker/issues

topics:
  - picker
  - camera
  - cropper
  - compressor
  - record

environment:
  sdk: ^2.17.0
  flutter: ">=3.3.10"

dependencies:
  flutter:
    sdk: flutter

  # Camera
  camera: ^0.11.0+2

  # Path provider
  path_provider: ^2.1.3

  # Toast
  fluttertoast: ^8.2.5

  # Crop
  image_cropper: ^8.0.2

  # File Picker
  file_picker: ^8.0.3

  # Compressor Video
  light_compressor: ^2.2.0

  # Recorder
  record: ^5.0.5

  # Stop watch timer
  stop_watch_timer: ^3.1.1

  # Http
  http: ^1.2.1

  # Uuid
  uuid: ^4.4.0

  # Cross file
  cross_file: ^0.3.4+1

  # Mime
  mime: ^1.0.5

  # Win32
  win32: ^5.5.5

  # Path
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: full_picker
      ios:
        default_package: full_picker
      linux:
        default_package: full_picker
      macos:
        default_package: full_picker
      web:
        default_package: full_picker
      windows:
        default_package: full_picker

screenshots:
  - description: Full Picker logo.
    path: screenshots/logo.png